### ISSUE TITLE
[USER STORY] Navigation bar

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#10]
As a **user** I can **see a navigation menu** so that **I can navigate with ease**

### Acceptance Criteria

- [x] A navigation menu is present across the entire site
- [x] Navigation links lead to the correct pages

### Tasks

- [x] Create navbar
- [x] Set up routing for nav links
