### ISSUE TITLE
[USER STORY] Routing

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#11]
As a **user** I can **navigate easily through pages** so that **I can browse the site without reloading the page**

### Acceptance Criteria

- [x] Navigation is intuitive
- [x] Navigating doesn't reload the page

### Tasks

- [x] Route navigation links correctly
- [x] Load components instead of pages
