### ISSUE TITLE
[USER STORY] Sign up

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#12]
As a **user** I can **create an account** so that **I can access member-only features**

### Acceptance Criteria

- [x] Users can sign up
- [x] A sign-up link is visible to all unauthenticated users
- [x] Signing up creates a new user with a profile

### Tasks

- [x] Create backend for user registration
- [x] Add profile creation to user registration
- [x] Create a sign-up page with a form
- [x] Link to the sign-up page
