### ISSUE TITLE
[USER STORY] Sign in

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#13]
As a **registered user** I can **sign in to the app** so that **I can use my account**

### Acceptance Criteria

- [x] Registered users can sign in
- [x] Signing in grants access to full app features

### Tasks

- [x] Create sign-in functionality
- [x] Create sign-in page with form
