### ISSUE TITLE
[USER STORY] Stay logged in

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#14]
As a **logged-in user** I can **stay logged-in until I choose to log out** so that **I can have a smooth experience**

### Acceptance Criteria

- [x] Users stay logged in until manually logging out
- [x] Refreshing the page does not log the user out
- [x] Leaving the page does not log the user out

### Tasks

- [x] Create a system for refreshing the authentication token
