### ISSUE TITLE
[USER STORY] Authentication status

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#15]
As a **user** I can **see whether or not I am signed in** so that **I can sign in or out as needed**

### Acceptance Criteria

- [x] Site users can see whether or not they're signed-in
- [x] Given an unauthenticated user, the navigation bar has links for signing up or signing in
- [x] Given an authenticated user, the navigation bar has a link for logging out

### Tasks

- [x] Create conditional rendering in the navbar
- [x] Display sign-in/up/out to reflect authenticated status
