### ISSUE TITLE
[USER STORY] Delete post

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#18]
As a **post owner** I can **delete my post** so that **I have control over my content**

### Acceptance Criteria

- [x] Signed in users can delete their own posts
- [x] Users can not delete other users' posts

### Tasks

- [x] Add deletion function to posts
- [x] Display a delete button on a signed-in user's own posts
- [x] Restrict deletion to the owner of the post
