### ISSUE TITLE
[USER STORY] View Recent Posts

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#19]
As a **user** I can **view all recent posts in sorted by latest first** so that **I can keep up with the newest content**

### Acceptance Criteria

- [x] Users can view all posts
- [x] The most recent posts appear at the top

### Tasks

- [x] Create list view for posts
- [x] Sort posts by newest first
