### ISSUE TITLE
[EPIC] - Authentication

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#2]
- [x] As a **user** I can **create an account** so that **I can access member-only features**
- [x] As a **registered user** I can **sign in to the app** so that **I can use my account**
- [x] As a **user** I can **see whether or not I am signed in** so that **I can sign in or out as needed**
- [x] As a **user** I can **stay logged-in until I choose to log out** so that **I can have a smooth experience**
