### ISSUE TITLE
[USER STORY] Feed of followed users

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#20]
As a **user** I can **choose to view only the content I follow** so that **I can find the most relevant content for me**

### Acceptance Criteria

- [x] Users can access a specific feed for followed users
- [x] The feed only displays posts by users whom the signed-in user followes

### Tasks

- [x] Create a page for the feed of followed users
- [x] Only display posts by the user's followed users
