### ISSUE TITLE
[USER STORY] Search posts

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#21]
As a **user** I can **search for specific posts** so that **I can find the content that I seek**

### Acceptance Criteria

- [x] Users find a search bar in the navigation bar
- [x] Upon submission, the search returns a list of posts filtered by the submitted keyword(s)

### Tasks

- [x] Create search query functionality
- [x] Add search feature to the navbar
