### ISSUE TITLE
[USER STORY] View post details

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#22]
As a **user** I can **open a single post** so that **I can see its details and comments**

### Acceptance Criteria

- [x] Clicking a post opens its detail page
- [x] On the post detail page, users can find the post details
- [x] Users can also see comments on the post detail page

### Tasks

- [x] Create a post detail view
- [x] Create a page for page details
- [x] Load all comments associated with the post
