### ISSUE TITLE
[USER STORY] Infinite scroll

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#23]
As a **user** I can **keep scrolling down the page to load more posts automatically** so that **I have a smooth experience**

### Acceptance Criteria

- [x] Posts load in chunks
- [x] Scrolling to the bottom automatically loads the next chunk
- [x] All posts can be seen if a user scrolls long enough

### Tasks

- [x] Paginate posts
- [x] Create endless scroll feature instead of pages
