### ISSUE TITLE
[USER STORY] Create a comment

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#25]
As a **signed-in user** I can **add my own comments to posts** so that **I can share what I think and feel about posts**

### Acceptance Criteria

- [x] Signed-in users can add comments to a post they're viewing
- [x] Clicking the comment button opens a commenting form
- [x] A submitted comment is added and displayed on the post page

### Tasks

- [x] Add comment button to posts
- [x] Create a comment form
- [x] Attach submitted comments to the associated post
