### ISSUE TITLE
[USER STORY] Delete comments

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#26]
As a **the owner of a comment** I can **delete the comment** so that **I can remove comments I no longer want to share**

### Acceptance Criteria

- [x] Given a signed-in user, a delete button appears next to the user's comments
- [x] Using the delete function deletes the comment from the database

### Tasks

- [x] Add delete button to owned comments
- [x] Create function for deleting comments
