### ISSUE TITLE
[USER STORY] Like posts

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#28]
As a **signed-in user** I can **like posts** so that **I can show my what content I like**

### Acceptance Criteria

- [x] Each post has a like button
- [x] Only signed-in users can like a post
- [x] Each user can only like any given post once

### Tasks

- [x] Add a like button
- [x] Create a like model instance when the button is clicked, only if no identical instance exists already
- [x] Restrict the like feature to signed-in users
