### ISSUE TITLE
[EPIC] - Posting

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#3]
- [x] As a **signed-in user** I can **create new posts** so that **I can show my images to other users**
- [x] As a **post owner** I can **edit the details of my post** so that **I can update posts or fix mistakes**
- [x] As a **post owner** I can **delete my post** so that **I have control over my content**
