### ISSUE TITLE
[USER STORY] Follow users

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#31]
As a **signed-in user** I can **follow users** so that **I can support users who post interesting content**

### Acceptance Criteria

- [x] Given a signed-in user, there's a button for following any other user of the app
- [x] Following a user adds them to a list of followed users, being followed adds the user to a list of followers
- [x] Numbers of followers and followed users are updated accordingly

### Tasks

- [x] Add a model for follower relations to the backend
- [x] Add a follow button next to user displays on the frontend
- [x] Create functions for following users and adding them to the associated lists
