### ISSUE TITLE
[USER STORY] View followed users' posts

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#32]
As a **signed-in user** I can **view a feed of only posts by users I follow** so that **I can see what they're posting**

### Acceptance Criteria

- [x] Given a signed-in user, there's a navigation link for a feed of followed users
- [x] The feed only displays posts by followed users

### Tasks

- [x] Create a filter for followed users' posts
- [x] Create a feed for this filtered post list
- [x] Add a link to the feed in the navbar of authenticated users
