### ISSUE TITLE
[USER STORY] Unfollow users

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#33]
As a **signed-in user** I can **unfollow my followed users** so that **I can remove their posts from my feed**

### Acceptance Criteria

- [x] When following a user, an unfollow button appears instead
- [x] Clicking the unfollow button deletes the follower/following relation

### Tasks

- [x] Create function for unfollowing a user
- [x] Add logic for displaying the correct follow/unfollow button based on following status
