### ISSUE TITLE
[USER STORY] Profile page

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#34]
As a **user** I can **view the profiles of other users** so that **I can see their content and profile information**

### Acceptance Criteria

- [x] Each user has a profile page
- [x] Clicking a username opens the profile

### Tasks

- [x] Create profile whenever a user is created
- [x] Add profile page
- [x] Add links to profile page on usernames
