### ISSUE TITLE
[USER STORY] User stats

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#36]
As a **user** I can **see the number of posts, follows and followed users of any profile** so that **I can learn more about the users**

- [x] Profile pages contain counters for followers, follows, and posts
- [x] Accurate counts are displayed for each

### Tasks

- [x] Add counters to profile page
- [x] Update count when changed
