### ISSUE TITLE
[USER STORY] Edit profile

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#38]
As a **signed-in user** I can **edit my profile** so that **I can update my avatar and profile information**

### Acceptance Criteria

- [x] Given a signed-in user, there's a button for updating the profile page
- [x] The button opens a form
- [x] Submitting the form updates the profile

### Tasks

- [x] Add profile editing form
- [x] Add "edit profile" button
- [x] Update the profile via the form
