### ISSUE TITLE
[USER STORY] Update username and password

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#39]
As a **signed-in user** I can **change my username and password** so that **I have control over my account**

### Acceptance Criteria

- [x] Registered users can update username and password
- [x] Credentials are updated upon submission

### Tasks

- [x] Add functionality for changing user credentials
