### ISSUE TITLE
[EPIC] - Browsing

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#4]
- [x] As a **user** I can **view all recent posts in sorted by latest first** so that **I can keep up with the newest content**
- [x] As a **user** I can **choose to view only the content I follow** so that **I can find the most relevant content for me**
- [x] As a **user** I can **search for specific posts** so that **I can find the content that I seek**
- [x] As a **user** I can **open a single post** so that **I can see its details and comments**
- [x] As a **user** I can **keep scrolling down the page to load more posts automatically** so that **I have a smooth experience**
