### ISSUE TITLE
[USER STORY] Block user

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#40]
As a **signed-in user** I can **block another user** so that **I do not have to see their posts**

### Acceptance Criteria

- [x] Given a signed-in user, the option appears for blocking another user
- [x] Blocking a user hides their content

### Tasks

- [x] Create a model for blocking users
- [x] Add a "block this user" button
- [x] Exclude content from blocked users in post list
