### ISSUE TITLE
[USER STORY] Add friends

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#43]
As an **authenticated user** I can **add followers to a list of friends** so that **I can have an inner circle of selected followers**

### Acceptance Criteria

- [x] Followers can be added to a list of friends
- [x] Friends can also be unfriended

### Tasks

- [x] Create model for friends
- [x] Add an "add friend" feature to the app
- [x] Add an "unfriend" feature to the app
