### ISSUE TITLE
[USER STORY] Friends only

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#44]
As an **authenticated user** I can **restrict the visibility of my post** so that **only followers on my friends list can see it**

### Acceptance Criteria

- [x] Posts have a visibility selector
- [x] When set to "friends only," the post is only visible to the user's friends

### Tasks

- [x] Add visibility selector to posts
- [x] Create filter for "friends only"
