### ISSUE TITLE
[EPIC] - Comment

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#5]
- [x] As a **user** I can **view comments on posts** so that **I can read other users' thoughts about the post**
- [x] As a **signed-in user** I can **add my own comments to posts** so that **I can share what I think and feel about posts**
- [x] As a **the owner of a comment** I can **delete the comment** so that **I can remove comments I no longer want to share**
- [x] As a **the owner of a comment** I can **edit the comment** so that **I can update comments and fix errors**
