### ISSUE TITLE
[EPIC] - Follow Users

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#7]
- [x] As a **signed-in user** I can **follow users** so that **I can support users who post interesting content**
- [x] As a **signed-in user** I can **view a feed of only posts by users I follow** so that **I can see what they're posting**
- [x] As a **signed-in user** I can **unfollow my followed users** so that **I can remove their posts from my feed**
