### ISSUE TITLE
[EPIC] - User Profile

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/pp5-frontend#8]
- [x] As a **user** I can **view the profiles of other users** so that **I can see their content and profile information**
- [x] As a **user** I can **see a list of the users with the most followers** so that ** I can see what's popular**
- [x] As a **user** I can **see the number of posts, follows and followed users of any profile** so that **I can learn more about the users**
- [x] As a **user** I can **view all of a user's posts from their profile page** so that **I can find their content and see whether I should follow them**
- [x] As a **signed-in user** I can **edit my profile** so that **I can update my avatar and profile information**
- [x] As a **signed-in user** I can **change my username and password** so that **I have control over my account**
